version: '3.8'

services:
  app:
    build: .
    container_name: cse3cwaass1-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    command: npm start

  db:
    image: postgres:16
    container_name: cse3cwaass1-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cse3cwa
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cse3cwa"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: